### ISSUE TITLE
Submit additional errata to author/publisher

### ISSUE THREAD

**Issue by jelaiw** [jelaiw/serious-cryptography-book-examples#1]
## Tasks
- [x] Check whether we have the latest errata from the publisher.
- [x] Organize raw epub annotations into "possible errata" collection.
- [x] Confirm each erratum and page number for submission.
- [x] Submit proposed errata items to publisher.
- [ ] Heads up to author.

## Links
* https://nostarch.com/seriouscrypto#updates.
* https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
* https://en.wikipedia.org/wiki/Erratum
  * *As a general rule, publishers issue an erratum for a production error (i.e., an error introduced during the publishing process) and a corrigendum for an author's error.*

**Comment by jelaiw** [comment]
Visited https://nostarch.com/seriouscrypto#updates and confirmed that the current errata are through the 8th printing.

**Comment by jelaiw** [comment]
Note, the epub I'm reading is the 7th printing.

**Comment by jelaiw** [comment]
According to https://nostarch.com/contactus, we should email errata@nostarch.com.
